# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: '3'

dotenv: ["../../nuvolaris-operator/.env"]

vars:
  BASETAG: 3.0.0-beta
  IMG: ghcr.io/nuvolaris/action
  TAG: 
    sh: git describe --tags --abbrev=0 2>/dev/null || git rev-parse --short HEAD

tasks:

  docker-login: 
    cmds:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin

  docker-setup:
    - docker buildx create --use
    - docker run -it --rm --privileged tonistiigi/binfmt --install all

  image-tag:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M) 
    - env PAGER= git tag

  ferretdb-openshift: >
      docker buildx build --platform linux/amd64,linux/arm64 
      -t ghcr.io/nuvolaris/ferretdb:1.6.0 ferretdb-openshift --push

  _nodejs:
    dir: openwhisk-runtime-nodejs
    cmds:
    - ./gradlew :core:nodejs{{.N}}Action:prepare
    - > 
      docker buildx build --platform linux/amd64,linux/arm64 
      -t {{.IMG}}-nodejs-v{{.N}}:{{.TAG}} core/nodejs{{.N}}Action/ --push
    - ./gradlew :core:nodejs{{.N}}Action:cleanup
 
  nodejs:
    cmds:
      - task: docker-setup
      - task: docker-login
      - task: _nodejs
        vars: 
          N: 16
      - task: _nodejs
        vars: 
          N: 18

  java:
    cmds:
      - |
        docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMG}}-java-v8:{{.TAG}} core/java8actionloop --push
    dir: openwhisk-runtime-java

  _python:
    dir: openwhisk-runtime-python/core
    cmds:
    - cp -Rvf python3Action/bin python{{.N}}Action
    - cp -Rvf python3Action/lib python{{.N}}Action
    - cp requirements_common.txt python{{.N}}Action
    - docker build python{{.N}}Action -t {{.IMG}}-python-v{{.N}}:{{.TAG}} --push

  # N=number of config: N=1
  # E=extension of test: E=py
  # R=runtime R=python-v311
  _test:
    - test -n "{{.N}}"
    - test -n "{{.E}}"
    - test -n "{{.R}}"
    - nuv config use "{{.N}}"
    - nuv setup nuvolaris login
    - nuv -wsk action update test test/hello.{{.E}} --docker {{.IMG}}-{{.R}}:{{.TAG}}
    - nuv -wsk action invoke test -r

  test:
    - task _test N=1 R=python-v311 E=py

  python:
      - task: docker-setup
      - task: docker-login
      - task: _python
        vars: 
          N: 310
      - task: _python
        vars: 
          N: 311

  